version: '3.8'

services:
  python_app:
    build:
      context: .
    environment:
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP:ja
      - LC_ALL=ja_JP.UTF-8
      - TZ=Asia/Tokyo
      - PYTHONUSERBASE=/home/pythonuser/.cache/pip
    volumes:
      - .:/app
      - cache:/home/pythonuser/.cache
      - fonts:/usr/share/fonts
    tty: true
volumes:
  cache:
    external: true
  fonts:
    external: true